name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com | sh
        sudo usermod -aG docker $USER
        newgrp docker

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        sudo apt-get install conntrack
        sudo minikube start --driver=none
        minikube status
        minikube update-context

    - name: Pull Docker image from Docker Hub
      run: |
        docker pull basudevpanda/dsc-mlops:latest
        minikube image load basudevpanda/dsc-mlops:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml

    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get svc
