name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t basudevpanda/dsc-mlops:latest .
        docker push basudevpanda/dsc-mlops:latest

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBECONFIG_CONTENTS" | base64 --decode > $HOME/.kube/config
      env: 
        KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG_CONTENTS }}

    - name: Create CA certificate file
      run: |
        echo "$K8S_CA_DATA" | base64 --decode > $HOME/.kube/ca.crt
      env:
        K8S_CA_DATA: ${{ secrets.K8S_CA_DATA }}

    - name: Create client certificate file
      run: |
        echo "$K8S_CLIENT_CERT_DATA" | base64 --decode > $HOME/.kube/client.crt
      env:
        K8S_CLIENT_CERT_DATA: ${{ secrets.K8S_CLIENT_CERT_DATA }}

    - name: Create client key file
      run: |
        echo "$K8S_CLIENT_KEY_DATA" | base64 --decode > $HOME/.kube/client.key
      env:
        K8S_CLIENT_KEY_DATA: ${{ secrets.K8S_CLIENT_KEY_DATA }}

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f prometheus.yaml
        kubectl apply -f grafana.yaml
