name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dsc-mlops:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dsc-mlops:latest

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBECONFIG_CONTENTS" > $HOME/.kube/config
      env:
        KUBECONFIG_CONTENTS: |
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: {{ secrets.K8S_CA_DATA }}
              server: https://172.28.179.85:8443
            name: minikube
          contexts:
          - context:
              cluster: minikube
              namespace: default
              user: minikube
            name: minikube
          current-context: minikube
          kind: Config
          preferences: {}
          users:
          - name: minikube
            user:
              client-certificate-data: {{ secrets.K8S_CLIENT_CERT_DATA }}
              client-key-data: {{ secrets.K8S_CLIENT_KEY_DATA }}

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f prometheus.yaml
        kubectl apply -f grafana.yaml
