apiVersion: v1
clusters:
  - cluster:
      certificate-authority: $HOME/.kube/ca.crt
      server: https://172.28.179.85:8443
      name: minikube
contexts:
  - context:  # No colon here, nested definition follows
     cluster: minikube
     namespace: default
     user: minikube
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: $HOME/.kube/client.crt
      client-key: $HOME/.kube/client.key
kind: Config
